spring:
  # DataSource Config
    datasource:
        url: jdbc:oracle:thin:@192.168.1.68:1521:clcm
        username: CLHE
        password: he
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000

    redis:
        host: 192.168.1.232
        port: 6379
        usePool: true

server:
    port: 7000

logging:
    level:
        com.example.demo.mapper : debug


appKey: huaerjinmai
v: 1.1
#apiHost: http://cljj.kmdns.net:81
apiHost: http://127.0.0.1:81/apiServer
channelId: 4000
secretKey: 1ed00303c7d4491fb57ab75878bbd229
selectUrl: /partner/queryHandler.go
channelUrl: /org/apiQueryHandler.go
accountUrl: /partner/accountHandler.go
bankUrl: /partner/bankHandler.go
walletUrl: /partner/walletHandler.go
toolsUrl: /base/toolsHandler.go
pageSize: 10